### ISSUE TITLE
Updates inquiry

### ISSUE THREAD

**Issue by ghost** [mdbootstrap/mdb-docs-and-content#96]
The company mdb promises to publish releases every two weeks, but there hasn't been an update since two months. If you try to complain publicly, your comment will be deleted. This is very anti-democratic, unresponsible and unfair against customers, who have paid many for this framework. This message is just a warning to all developers who have thought about buying this product. We will probably file a complaint against this company.

**Comment by filipkappa** [comment]
Hello,

Please reach out directly to contact@mdbootstrap.com

If you are not able to access the latest updates you will be granted a refund.

Please note, that we offer "Unlimited Updates":
https://mdbootstrap.com/general/license/
https://mdbootstrap.com/docs/standard/pro/
https://mdbootstrap.com/docs/standard/pro/updates/

"Unlimited Updates" means that you get access to every new update released when your subscription is active, you also retain the access to all of those version when your subscription expires.

It's true that we usually release updates every two weeks, and it's possible that this has been mentioned as an estimation in some answers on the support forum.

When users ask about the ETA for some features we try to give them the best prediction based on the history of releases and the product roadmap. 

We also try to keep changelogs and roadmaps up to date, so this information is public and available to you:
https://mdbootstrap.com/docs/standard/getting-started/changelog/
https://mdbootstrap.com/docs/b5/roadmap/

As you see, in most cases we release updates every 2 weeks, but there are occasions on which there is something else that needs an imminent fix. 

For example, we recently optimized & migrated the entire MDB5 documentation to Hugo, in order to make it faster and more pleasant to use. Such projects can delay releases sometimes, but luckily they happen sporadically. 

**Of course there is nothing worse than a disappointed customer, so if there was a promise that was made to you, it will be kept. Please reach out to us via contact@mdbootstrap.com**

I just want you to know that if anything like this happened, it was most probably a misunderstanding or a mistake. Our policy regarding updates is the same as always. I can imagine that you may have received a misworded answer from our staff, and in that case we will of course grant you the benefits you expected or if that's out of reach - we will refund your order.

I hope this clears things up ;)
Best regards,
